create table public.projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  slug character varying not null,
  status character varying null default 'in-progress'::character varying,
  collaborators text null default '[]'::text,
  constraint projects_pkey primary key (id)
) TABLESPACE pg_default;